name: Pytest and Docker

on:
  pull_request:
    branches:
      - master

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Makefile
        run: make run_pytest
      - name: Build Docker image
        run: docker build -t my-image .
      - name: Run test in container
        run: make ci
